<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWEeuLRe\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWEeuLRe/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWEeuLRe.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWEeuLRe\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWEeuLRe\App_KernelDevDebugContainer([
    'container.build_hash' => 'WEeuLRe',
    'container.build_id' => 'b3c0ac3c',
    'container.build_time' => 1727629401,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWEeuLRe');
