<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app_api_countryapp_api_country_root' => [[], ['_controller' => 'App\\Controller\\CountryController::getAll'], [], [['text', '/api/country']], [], [], []],
    'app_api_countryapp_api_country_code' => [['code'], ['_controller' => 'App\\Controller\\CountryController::get'], [], [['variable', '/', '[^/]++', 'code', true], ['text', '/api/country']], [], [], []],
    'app_api_countryapp_api_country_add' => [[], ['_controller' => 'App\\Controller\\CountryController::add'], [], [['text', '/api/country']], [], [], []],
    'app_api_rootapp_api_root_index' => [[], ['_controller' => 'App\\Controller\\RootController::index'], [], [['text', '/api/']], [], [], []],
    'app_api_rootapp_api_root_ping' => [[], ['_controller' => 'App\\Controller\\RootController::ping'], [], [['text', '/api/ping']], [], [], []],
    'App\Controller\CountryController::getAll' => [[], ['_controller' => 'App\\Controller\\CountryController::getAll'], [], [['text', '/api/country']], [], [], []],
    'App\Controller\CountryController::get' => [['code'], ['_controller' => 'App\\Controller\\CountryController::get'], [], [['variable', '/', '[^/]++', 'code', true], ['text', '/api/country']], [], [], []],
    'App\Controller\CountryController::add' => [[], ['_controller' => 'App\\Controller\\CountryController::add'], [], [['text', '/api/country']], [], [], []],
    'App\Controller\RootController::index' => [[], ['_controller' => 'App\\Controller\\RootController::index'], [], [['text', '/api/']], [], [], []],
    'App\Controller\RootController::ping' => [[], ['_controller' => 'App\\Controller\\RootController::ping'], [], [['text', '/api/ping']], [], [], []],
];
